Updated backend to return status of tickets filed on artifact requests
STEELISI/classnet-backend pull request #19
Opened 2023-04-11 18:00 UTC by paulkurian-usc

2023-04-11 20:42 UTC, hardaker requested changes

2023-04-11 20:42 UTC, hardaker commented on searcch_backend/api/ticket_creation/x.py
is this file needed?  it looks like a test script that you were using for local testing.  maybe I'm wrong though.

2023-04-14 19:00 UTC, paulkurian-usc commented on searcch_backend/api/ticket_creation/x.py
Sorry about that, it is a test script like you mentioned. I have removed it in this commit: 3e6e0a731469c5cf6d9c2f238c08d42c65537b54

2023-04-14 19:39 UTC, hardaker approved these changes

2023-04-14 19:39 UTC, merged